export const SYMPTOM_MAP = {
  fever: 'Fever',
  feverOnsetDate: 'Onset date:',
  feverTemperature: 'Highest temp:',
  feverDays: 'Duration (days):',
  abdominalPain: 'Abdominal pain',
  chills: 'Chills',
  cough: 'Cough',
  coughOnsetDate: 'Onset date:',
  coughDays: 'Duration (days):',
  coughSeverity: 'Severity:',
  diarrhea: 'Diarrhea',
  difficultyBreathing: 'Difficulty breathing',
  headache: 'Headache',
  muscleAches: 'Muscle aches / pain',
  soreThroat: 'Sore throat',
  vomiting: 'Vomiting',
  other: 'Other',
};
